apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-timesheet-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: super-timesheet
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: super-timesheet
#      annotations:
#        prometheus.io/scrape: "true"
#        prometheus.io/path: /metrics
#        prometheus.io/port: "3000"
    spec:
      containers:
        - name: super-timesheet
          image: IMAGE_VERSION
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 300Mi
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node.kubernetes.io/lifecycle
                operator: In
                values:
                  - spot
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - super-timesheet
                topologyKey: kubernetes.io/hostname
              weight: 99
      imagePullSecrets:
        - name:  ocisecret
